import { GraphNode } from '../types';

export const initialNodes: GraphNode[] = [
  // --- DOMAIN 1: COGNITIVE PSYCHOLOGY ---
  {
    id: 'dom_cog_psy',
    type: 'domain',
    title: 'Cognitive Science & Psychology',
    subtitle: 'The mechanisms of human attention, memory, and information processing.',
    content: 'Cognitive Science explores the intricate pathways through which human beings gather, synthesize, store, and retrieve information. Within Cortex, this domain focuses on mapping how digital interfaces interact with biological neurological limits, analyzing concepts such as selective attention, sensory overload, and executive function fatigue.',
    readingTimeMin: 1,
    cognitiveLoad: 3,
    signalScore: 98,
    utilityValue: 9.4,
    humanVerifications: 342,
    citations: ['Neisser, U. (1967). Cognitive Psychology.', 'Kahneman, D. (2011). Thinking, Fast and Slow.']
  },
  {
    id: 'sub_attention',
    type: 'subject',
    parentId: 'dom_cog_psy',
    title: 'Attentional Selection Mechanisms',
    subtitle: 'How the human brain filters noise to select valuable input signals.',
    content: 'Attentional selection is the gatekeeper of consciousness. Because the environment presents far more sensory data than the brain can process in real-time, neurological bottlenecking is inevitable. This subject explores theories of how and where the brain applies filters to screen out irrelevant visual and auditory stimulation.',
    readingTimeMin: 3,
    cognitiveLoad: 5,
    signalScore: 96,
    utilityValue: 9.1,
    humanVerifications: 189,
    citations: ['Broadbent, D. E. (1958). Perception and Communication.', 'Treisman, A. M. (1964). Selective attention in man.']
  },
  {
    id: 'ins_cognitive_load',
    type: 'insight',
    parentId: 'sub_attention',
    title: 'Cognitive Load Theory (CLT)',
    subtitle: 'The hard bottleneck of working memory limits.',
    content: 'Cognitive Load Theory posits that human working memory can only hold a very limited number of information chunks (traditionally 7±2, modern consensus indicates 4±1) at any given moment. Digital noise—such as auto-playing videos, notification sounds, and flashy animations—consumes extraneous cognitive load, directly reducing the brain\'s capacity to process germane (useful) learning material.',
    readingTimeMin: 4,
    cognitiveLoad: 6,
    signalScore: 99,
    utilityValue: 9.7,
    humanVerifications: 412,
    citations: ['Sweller, J. (1988). Cognitive load during problem solving.', 'Miller, G. A. (1956). The magical number seven, plus or minus two.'],
    takeaways: [
      'Working memory represents a strict biological bottleneck with a capacity of 4±1 active information units.',
      'Extraneous cognitive load is generated by poor interface design, flashing ads, and fragmented content flows.',
      'Maximizing germane cognitive load requires structured, static, high-contrast layouts that align with mental schemas.'
    ]
  },
  {
    id: 'dd_working_memory',
    type: 'deep_dive',
    parentId: 'ins_cognitive_load',
    title: 'Working Memory Overload & The Split-Attention Effect',
    subtitle: 'An empirical analysis of split-attention and cognitive breakdown in multi-feed layouts.',
    content: 'When instructional material or reading content forces the reader\'s eye to constantly alternate between non-integrated elements (e.g., jumping between text, interactive dynamic widgets, and unrelated sidebar ads), a "Split-Attention Effect" occurs. The visual system must repeatedly search the layout, locate the relevant target, and establish context anew. This repeated context-switching triggers rapid depletion of glucose and oxygen in the prefrontal cortex. Empirically, subjects exposed to split-attention interfaces show a 42% decrease in long-term schema integration and high scores on the NASA Task Load Index (TLX) for mental effort.',
    readingTimeMin: 8,
    cognitiveLoad: 8,
    signalScore: 99,
    utilityValue: 9.8,
    humanVerifications: 215,
    citations: [
      'Chandler, P., & Sweller, J. (1991). Cognitive Load Theory and the Format of Instruction.',
      'Mayer, R. E., & Moreno, R. (2003). Nine ways to reduce cognitive load in multimedia learning.'
    ],
    takeaways: [
      'Split-attention forces high-frequency visual searches that rapidly deplete prefrontal cortex resources.',
      'Integrating visual explanatory elements directly with relevant text eliminates search-and-compare fatigue.',
      'Cortex interfaces enforce contiguous text layouts with zero dynamic interruptions to prevent split-attention fatigue.'
    ]
  },

  // --- DOMAIN 2: INFORMATION THEORY ---
  {
    id: 'dom_info_theory',
    type: 'domain',
    title: 'Information Theory & Systems',
    subtitle: 'The mathematical study of coding, transmitting, and purifying data signals.',
    content: 'Information Theory provides the mathematical foundation for understanding how data is encoded, transmitted over noisy channels, and decoded. By treating human-computer interaction as a channel-capacity problem, we can mathematically optimize the density of knowledge and minimize extraneous digital noise.',
    readingTimeMin: 2,
    cognitiveLoad: 5,
    signalScore: 97,
    utilityValue: 9.2,
    humanVerifications: 288,
    citations: ['Shannon, C. E. (1948). A Mathematical Theory of Communication.']
  },
  {
    id: 'sub_signal_processing',
    type: 'subject',
    parentId: 'dom_info_theory',
    title: 'Information Entropy & Signal Dynamics',
    subtitle: 'Quantifying surprise and measuring communication signal purity.',
    content: 'Digital platforms function as noisy communication channels. When a platform maximizes engagement via algorithmically randomized feeds, it introduces high-entropy noise designed to trigger dopamine response. True signal dynamics focus on optimizing the delivery of structured, highly informative bytes of data with predictable semantic structures.',
    readingTimeMin: 4,
    cognitiveLoad: 6,
    signalScore: 95,
    utilityValue: 8.8,
    humanVerifications: 142,
    citations: ['Cover, T. M., & Thomas, J. A. (2006). Elements of Information Theory.']
  },
  {
    id: 'ins_snr_ux',
    type: 'insight',
    parentId: 'sub_signal_processing',
    title: 'The Signal-to-Noise Ratio (SNR) of User Interfaces',
    subtitle: 'A formal metric for interface readability and cognitive yield.',
    content: 'The Signal-to-Noise Ratio (SNR) in UX represents the ratio of relevant information (the "signal") to irrelevant distraction (the "noise"). Standard social feeds operate at an SNR below 0.1, where 90% of screen elements—auto-playing feeds, interactive gamified counters, trending tabs, and badges—constitute structural noise. Cortex mandates a target SNR of >10.0, eliminating all non-essential visual markers.',
    readingTimeMin: 5,
    cognitiveLoad: 7,
    signalScore: 98,
    utilityValue: 9.5,
    humanVerifications: 301,
    citations: ['Woodson, W. E., et al. (1992). Human Factors Design Handbook.', 'Lidwell, W., et al. (2003). Universal Principles of Design.'],
    takeaways: [
      'Interface SNR is mathematically modeled as: SNR = (Useful Information Bits) / (Total Visual/Interactive Stimuli Bits).',
      'High-SNR designs reduce the search phase of visual perception from several seconds to milliseconds.',
      'Eliminating arbitrary counters, like "Likes" or "Retweets", decreases performance anxiety and visual clutter.'
    ]
  },
  {
    id: 'dd_shannon_entropy',
    type: 'deep_dive',
    parentId: 'ins_snr_ux',
    title: 'Shannon Entropy and Cognitive Satiation',
    subtitle: 'Applying information-theoretic models to digital attention spans.',
    content: 'Shannon entropy measures the uncertainty or "surprise" associated with a random variable. In algorithmic feeds, high information entropy is artificially maintained: the user does not know if the next swipe will yield a highly stimulating video, an advertisement, or a friend\'s photo. This random interval reinforcement schedule exploits biological evolutionary mechanisms, keeping the brain in a state of chronic vigilance. By introducing structured, predictable node-based paths, Cortex reduces information entropy to near-zero. Users select their domain of inquiry ahead of time, ensuring that each subsequent click provides high semantic resolution with low mechanical surprise. This matches the cognitive expectations of researchers, promoting rapid intellectual satiation rather than additive cravings.',
    readingTimeMin: 9,
    cognitiveLoad: 9,
    signalScore: 99,
    utilityValue: 9.6,
    humanVerifications: 176,
    citations: [
      'Shannon, C. E. (1949). Communication in the Presence of Noise.',
      'Berridge, K. C., & Robinson, T. E. (1998). What is the role of dopamine in reward: wanting or liking?'
    ],
    takeaways: [
      'Artificially high platform entropy exploits dopamine receptors through variable reward schedules.',
      'Low entropy layouts promote structured, goal-driven discovery where the user remains in complete executive control.',
      'Satiation is achieved when a structured line of inquiry is completely explored, triggering healthy neural rest.'
    ]
  },

  // --- DOMAIN 3: CHOICE ARCHITECTURE ---
  {
    id: 'dom_choice_arch',
    type: 'domain',
    title: 'Choice Architecture & Behavioral Economics',
    subtitle: 'The engineering of digital environments and their impact on human decisions.',
    content: 'Choice Architecture analyzes how the presentation of options influences human decision-making. In digital ecosystems, interface elements act as powerful nudges. Cortex re-engineers this architecture to default toward focus, deep consideration, and cognitive sovereignty.',
    readingTimeMin: 2,
    cognitiveLoad: 4,
    signalScore: 96,
    utilityValue: 9.0,
    humanVerifications: 250,
    citations: ['Thaler, R. H., & Sunstein, C. R. (2008). Nudge: Improving Decisions About Health, Wealth, and Happiness.']
  },
  {
    id: 'sub_dark_patterns',
    type: 'subject',
    parentId: 'dom_choice_arch',
    title: 'Digital Exploitation of Cognitive Biases',
    subtitle: 'Analyzing how engagement-first platforms manipulate human neurological heuristics.',
    content: 'Standard social networks weaponize cognitive biases—such as Loss Aversion, Social Proof, and the Zeigarnik Effect—to maximize user session lengths. This subject deconstructs the mechanics of infinite scroll, push notifications, and visual urgency tags, illustrating how they hijack human executive functions.',
    readingTimeMin: 3,
    cognitiveLoad: 6,
    signalScore: 98,
    utilityValue: 9.3,
    humanVerifications: 211,
    citations: ['Fogg, B. J. (2009). A behavior model for persuasive design.']
  },
  {
    id: 'ins_infinite_scroll_fatigue',
    type: 'insight',
    parentId: 'sub_dark_patterns',
    title: 'The Neurological Costs of the Infinite Scroll',
    subtitle: 'How continuous content presentation paralyzes active decision-making.',
    content: 'The infinite scroll eliminates natural cognitive boundaries (called "stopping cues"). On physical pages or structured directories, the reader encounters a logical end-point, which naturally prompts them to reflect, change activities, or close the source. The infinite scroll bypasses this reflective pause by continuously loading new stimuli. This prevents the brain\'s default mode network (DMN) from activating, causing immediate mental fatigue, decision paralysis, and severe attention span fragmentation.',
    readingTimeMin: 5,
    cognitiveLoad: 7,
    signalScore: 99,
    utilityValue: 9.6,
    humanVerifications: 388,
    citations: ['Aharoni, E., et al. (2020). The neuroscience of scrolling: Focus and fatigue.', 'Harris, T. (2016). How Technology Hijacks People\'s Minds.'],
    takeaways: [
      'Infinite scrolling destroys organic "stopping cues," trapping the user in an unreflective consumption loop.',
      'The human brain requires explicit structural boundaries to evaluate whether to continue an activity.',
      'Re-establishing hard visual and functional stopping points restores active mental governance.'
    ]
  },
  {
    id: 'dd_choice_overload_heuristics',
    type: 'deep_dive',
    parentId: 'ins_infinite_scroll_fatigue',
    title: 'Choice Overload, Hick\'s Law, and Cognitive Paralysis',
    subtitle: 'A mathematical analysis of cognitive friction in decision environments.',
    content: 'Hick\'s Law states that the time it takes to make a decision increases logarithmically with the number and complexity of choices presented: T = b * log2(n + 1). On current digital platforms, users are perpetually presented with dozens of conflicting options on a single viewport: trending topics, suggested accounts, nested threads, advertisements, and reactions. This creates a state of chronic "Choice Overload," which overwhelms the prefrontal cortex\'s capacity for deliberate, rational calculation. To cope, the brain downgrades its processing style from slow, analytic, rational consideration (System 2) to rapid, emotional, highly reactive heuristics (System 1). By severely restricting options to a simple hierarchical choice—either proceed to the next contiguous node or suspend the session—Cortex simplifies the cognitive environment, allowing System 2 analytical processing to remain active and unfatigued.',
    readingTimeMin: 7,
    cognitiveLoad: 8,
    signalScore: 98,
    utilityValue: 9.4,
    humanVerifications: 194,
    citations: [
      'Hick, W. E. (1952). On the rate of gain of information.',
      'Iyengar, S. S., & Lepper, M. R. (2000). When choice is demotivating: Can one desire too much of a good thing?'
    ],
    takeaways: [
      'Excessive visual and interactive options trigger an automatic fallback to reactive, low-effort System 1 heuristics.',
      'Eliminating auxiliary layout choices protects the prefrontal cortex from decision fatigue.',
      'The Cortex Node architecture ensures that the user is presented with exactly one primary logical continuation path.'
    ]
  }
];
